Added support for ZTD feature
open-switch/rootfs pull request #11
Opened 2018-08-24 05:35 UTC by skg-net

Signed-off-by: Senthil Kumar Ganesan <skg.net.dev@gmail.com>

2018-08-24 18:01 UTC, theucke commented on rootconf/etc/dhclient.conf
> +#supersede domain-name "fugue.com home.vix.com";
What are these about?

2018-08-24 18:08 UTC, heucke requested changes
Update the version, at least.

2018-08-24 18:08 UTC, theucke commented on VERSION
> +1.0.9
Since you're adding a feature, bump the minor version number instead. `1.1.0`

2018-08-24 18:08 UTC, theucke commented on rootconf/etc/ztd
> +         if [ $? -eq 0 ]; then
You can check the exit code directly like this:

```bash
if $ZTD_PROV_SCRIPT; then
```

> https://github.com/koalaman/shellcheck/wiki/SC2181

2018-08-24 18:08 UTC, theucke commented on rootconf/etc/ztd
> +   curl -o $ZTD_PROV_SCRIPT $new_ztd_provision_url
Double quote the variables. `$new_ztd_provision_url` is an external variable.

> https://github.com/koalaman/shellcheck/wiki/SC2086

2018-08-24 18:08 UTC, theucke commented on rootconf/etc/ztd
> +#!/bin/sh
This single file has 3-space indentation, 4-space indentation, and 6-space indentation.

2018-08-24 22:32 UTC, skg-net commented
Pull-request updated, HEAD is now da1a89f04eb01481f292f3e59f1a0be3ce86f6b2

2018-08-24 22:33 UTC, skg-net commented
@theucke addressed the review comments, please check.

2018-08-27 15:42 UTC, heucke approved these changes

2018-08-27 16:24 UTC, merged